name: Publish to gh-pages

on:
  repository_dispatch:
  push:
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
    - uses: actions/checkout@v2
    - name: Build tailwind
    - run: npx tailwindcss --input src/tailwind.css --output docs/styles/tailwind.css --watch
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs